apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test
  namespace: default
spec:
  interval: 30s
  url: https://github.com/mikebaum/gitops-test.git
  ref:
    branch: main

